Feat/commitments form
CollActionteam/collaction_cms pull request #68
Opened 2023-04-14 23:51 UTC by dromerolovo

Working UI with `CommitmentsBloc` integration.

The purpose of this PR is to consolidate all sections of the form to prepare for the following changes:
- Review and implement the form controllers with their respective validation and factory method
- Implement the integration between all the sections of the form and the bloc
- test the repository with the CrowdAction provided by the form.

2023-04-21 03:48 UTC, andre-tm-hui requested changes
Few things I've noticed with functionality:
- When removing a commitment, the following commitment becomes expanded. Seems like the expanded state of a commitment is tied to the index instead of the commitment itself. An easy fix might be to only allow one expanded commitment at a time, and close all expanded commitments when any commitment is removed.
- Maybe we can make it such that the `TagsField` has to have at least one item, and if a user tries to delete the last item, nothing happens? That might just come down to preference though.
- Minor thing, maybe we can use a `NumberFormat` and `TextFieldController` for the `PointsField` to force the input to be a number, similar to in `TimePicker/NumberField`.
- Another minor thing, but clicking in and out of `Create from scratch` after having added a commitment causes all the error messages to show up. Any way to make them not appear on a new form?
Also one thing I just want to clarify - with blocking commitments, a block shouldn't go two ways right? I.e. if A blocks B, should B also block A?
Besides that, code looks good.

2023-04-21 03:48 UTC, andre-tm-hui commented on lib/application/crowdaction/crowdaction_creation/commitments/commitments_bloc.dart
> +    // emit(CommitmentsState.commitmentsSet([
Is this going to be used?

2023-04-21 03:48 UTC, andre-tm-hui commented on lib/presentation/crowdactions/crowdaction_form/sections/commitments_section/assigned_commitments/commitment_item_form.dart
> +              child: CollactionTextFormField(
We should add a small issue to change this to `CollActionTextFormField`, correct the capitalization.

2023-04-21 03:48 UTC, andre-tm-hui commented on macos/Flutter/ephemeral/Flutter-Generated.xcconfig
Add to .gitignore

2023-04-21 03:48 UTC, andre-tm-hui commented on macos/Flutter/ephemeral/flutter_export_environment.sh
Add to .gitignore

2023-04-24 21:23 UTC, dromerolovo commented on lib/application/crowdaction/crowdaction_creation/commitments/commitments_bloc.dart
> +    // emit(CommitmentsState.commitmentsSet([
I don't think so, I'm going to get rid off this.

2023-04-24 21:23 UTC, dromerolovo commented on lib/presentation/crowdactions/crowdaction_form/sections/commitments_section/assigned_commitments/commitment_item_form.dart
> +              child: CollactionTextFormField(
Yes, good idea.

2023-04-24 21:24 UTC, dromerolovo commented on macos/Flutter/ephemeral/Flutter-Generated.xcconfig
We are not going to have macos and other platforms directories anymore. This will change with https://github.com/CollActionteam/collaction_cms/pull/53. But I'll remove the directories anyway

2023-04-24 22:10 UTC, dromerolovo commented
@andre-tm-hui 

The thing about **point 2** is that it can be frustrating for users if they want to delete all values and then add another. Currently, the behavior is a bit odd also because the last value is added when there are no values after expanding or contracting the `CommitmentItem`. This happens because the validation is producing an error, and the updated values are not stored in the bloc. So the last values are fetched again from the bloc. To address this for now, we could pass 'true' in the `buttonTriggered` parameter so that error messages will be displayed if the field is empty. Then, we can come up with how to maintain the state if a field is empty. 

Regarding **point 3** I think that there is more common to be able to write incorrect values, that not having the possibility of writing, take as an example EasyApply form in linkedin. You can write letters in numeric fields and of course you'll get the error message.

Regarding blocks, it might be cases that block A could block B and the other way around, shouldn't be a problem.

Regarding your last point, Yes definitely, we should add `injection.config.dart` for example.

2023-04-25 01:00 UTC, andre-tm-hui commented
I think if the weird behaviour could be fixed, that solves 2 and 3 automatically - the most jarring thing with that part of the UI is that the tick/indicator of a commitment's validity changes correctly if a field becomes invalid, and stays correct when the commitment is closed. However, when you open that commitment again, it suddenly becomes valid.

For now, passing `buttonTriggered` as `true` seems good enough though.

2023-04-25 01:14 UTC, dromerolovo commented
> I think if the weird behaviour could be fixed, that solves 2 and 3 automatically - the most jarring thing with that part of the UI is that the tick/indicator of a commitment's validity changes correctly if a field becomes invalid, and stays correct when the commitment is closed. However, when you open that commitment again, it suddenly becomes valid.
> 
> For now, passing `buttonTriggered` as `true` seems good enough though.

Yes, Agree. And That's happening because what explain in the previous comment, when I made a reference to the **point 2** I'll think of a solution and create a separate issue because is not critical, just weird.

2023-04-25 04:10 UTC, merged